[package]
name = "xs-windows-route-manager"
publish = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
ipnet.workspace = true
serde.workspace = true
serde_json.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true
xs-windows-private-storage = { path = "../windows-private-storage" }

[lints.rust]
unsafe_code = "deny"
unsafe_op_in_unsafe_fn = "deny"

[lints.clippy]
all = "warn"
pedantic = "warn"
