#ifndef XSNET_IOCTL_H
#define XSNET_IOCTL_H

#include <winioctl.h>
#include <stdint.h>

#define XSNET_DEVICE_TYPE UINT32_C(0x8337)
#define XSNET_IOCTL_ACCESS (FILE_READ_ACCESS | FILE_WRITE_ACCESS)

#define IOCTL_XSNET_HELLO \
    CTL_CODE(XSNET_DEVICE_TYPE, 0x800, METHOD_BUFFERED, XSNET_IOCTL_ACCESS)
#define IOCTL_XSNET_ATTACH \
    CTL_CODE(XSNET_DEVICE_TYPE, 0x801, METHOD_BUFFERED, XSNET_IOCTL_ACCESS)
#define IOCTL_XSNET_SET_LINK \
    CTL_CODE(XSNET_DEVICE_TYPE, 0x802, METHOD_BUFFERED, XSNET_IOCTL_ACCESS)
#define IOCTL_XSNET_DEQUEUE_TX \
    CTL_CODE(XSNET_DEVICE_TYPE, 0x803, METHOD_OUT_DIRECT, XSNET_IOCTL_ACCESS)
#define IOCTL_XSNET_ENQUEUE_RX \
    CTL_CODE(XSNET_DEVICE_TYPE, 0x804, METHOD_IN_DIRECT, XSNET_IOCTL_ACCESS)
#define IOCTL_XSNET_DETACH \
    CTL_CODE(XSNET_DEVICE_TYPE, 0x805, METHOD_BUFFERED, XSNET_IOCTL_ACCESS)

#endif
